### ISSUE TITLE
Техническое поражение

### ISSUE THREAD

**Issue by vaksenov77** [pepelazz/axe_bug_report#9]
При проведении матча необходимо созадть возможность технического поражения с указанием причины выбором из списка. Список отдельнным справочником

**Comment by pepelazz** [comment]
@vaksenov77 
справочник делаем отдельной таблицей? или там заранее известный небольшой набор вариантов и тогда эти варианты можно прописать в коде

**Comment by vaksenov77** [comment]
> @vaksenov77 справочник делаем отдельной таблицей? или там заранее известный небольшой набор вариантов и тогда эти варианты можно прописать в коде

Отдельной таблицей
